### ISSUE TITLE
T-SNE

### ISSUE THREAD

**Issue by xiuhaoLiang** [weichennone/FedMAX#5]
Hello, I am very interested in the picture of "t-SNE embedding of the activation vectors" in your paper. Could you please provide us with this part? thanks.（E-Mail：xiuhao2733@163.com）.

**Comment by xiuhaoLiang** [comment]
Hello, I am very interested in the picture of "t-SNE embedding of the activation vectors" in your paper. Could you please provide us with the code for this part? thanks.（E-Mail：xiuhao2733@163.com）.

**Comment by weichennone** [comment]
Sure, I've uploaded the code for T-SNE to
"digit_object_recognition/utils/tsne.py". You can refer to it as an
example.
To preserve the completeness of the rest of my code, I didn't change them.
But if you would like to recreate the plot from the paper, you can save the
activation of each client (models/Update.py) and gather them at the server
(models/Fed.py). That's where I created the T-SNE plot.
Hope this helps.

xiuhaoLiang ***@***.***> 于2021年11月28日周日 上午5:07写道：

**Comment by xiuhaoLiang** [comment]
Many thanks.

**Comment by xiuhaoLiang** [comment]
I still have a question. The activation vectors in the T-SNE plot are the activation vectors of the global model?

**Comment by xiuhaoLiang** [comment]
Now, I get it. The activation of each client (models/Update.py) is saved.  Gather them at the server, and use FedAvg (models/Fed.py) to aggregate them. Finally, the activation vectors in the T-SNE plot are got?

**Comment by xiuhaoLiang** [comment]
Now, I get it. The activation of each client (models/Update.py) is saved.  Gather them at the server, and use FedAvg (models/Fed.py) to aggregate them. Finally, the activation vectors in the T-SNE plot are got?

**Comment by weichennone** [comment]
> Now, I get it. The activation of each client (models/Update.py) is saved. Gather them at the server, and use FedAvg (models/Fed.py) to aggregate them. Finally, the activation vectors in the T-SNE plot are got?

That's right. You get the idea

**Comment by xiuhaoLiang** [comment]
> > Now, I get it. The activation of each client (models/Update.py) is saved. Gather them at the server, and use FedAvg (models/Fed.py) to aggregate them. Finally, the activation vectors in the T-SNE plot are got?
> 
> That's right. You get the idea

Okay, thank you.

**Comment by weichennone** [comment]
> > > Now, I get it. The activation of each client (models/Update.py) is saved. Gather them at the server, and use FedAvg (models/Fed.py) to aggregate them. Finally, the activation vectors in the T-SNE plot are got?
> > 
> > 
> > That's right. You get the idea
> 
> Okay, thank you.

Sure, no problem!

**Comment by xiuhaoLiang** [comment]
Bro, I draw the T-SNE plot by your method, but it may be wrong. Could you see my code and figure, and point out my fault? Thanks, bro.
[T-SNE.docx](https://github.com/weichennone/FedMAX/files/7658629/T-SNE.docx)

**Comment by weichennone** [comment]
> Bro, I draw the T-SNE plot by your method, but it may be wrong. Could you see my code and figure, and point out my fault? Thanks, bro. [T-SNE.docx](https://github.com/weichennone/FedMAX/files/7658629/T-SNE.docx)

It seems you only plot the activations of the global model. Not sure if it is what you meant. But if you are trying to recreate the plot from my paper, the activations of local clients, you need to store their activations instead of averaging them in "FedAvg_TSNE". You may try to plot the activation directly from "aggregration_users_activation".

**Comment by xiuhaoLiang** [comment]
> Do you mean that the activations of local clients are drawn one by one in only one T-SNE plot? By the way, what are the experimental conditions of the "Mitigating Activation Divergence" part of your paper, that is, the number of client training and batch size (local_ep and local_bs in the code)?

**Comment by weichennone** [comment]
> > Do you mean that the activations of local clients are drawn one by one in only one T-SNE plot? By the way, what are the experimental conditions of the "Mitigating Activation Divergence" part of your paper, that is, the number of client training and batch size (local_ep and local_bs in the code)?

Yes. For example, I use "A" representing the 1st client, "B" representing the 2nd client, etc. 
The number of clients is 10. I don't remember the exact batch size, maybe ~50. But the larger the batch size, the clearer you can see the pattern. The trade-off is, large batch size takes longer time to calculate T-SNE vectors.

**Comment by xiuhaoLiang** [comment]
> > > 您的意思是本地客户的激活是在一个T-SNE图中逐个绘制的吗？顺便问一下，您的论文中的“缓解激活差异”部分的实验条件是什么，即客户培训的数量和批大小(代码中的local_ep和local_bs)？
> 
> 是。例如，我使用“A”表示第一个客户端，“B”表示第二个客户端，等等。客户的数量是10，我不记得确切的批次大小，可能是50。但批处理的大小越大，您就越能清楚地看到模式。权衡的是，大批量计算T-SNE向量需要更长的时间.

Thanks. What is the number of iterations of client training? Do you see my code is correct? Various colors represent the activation vectors for different classes, while the letters denote the device IDs. How to ensure that various colors represent different types of activation vectors? plt.text(X[i, 0], X[i, 1], user_list[i // batch_size], color=color_list[i // batch_size])
[T-SNE_V1.docx](https://github.com/weichennone/FedMAX/files/7665415/T-SNE_V1.docx)

**Comment by weichennone** [comment]
> > > > 您的意思是本地客户的激活是在一个T-SNE图中逐个绘制的吗？顺便问一下，您的论文中的“缓解激活差异”部分的实验条件是什么，即客户培训的数量和批大小(代码中的local_ep和local_bs)？
> > 
> > 
> > 是。例如，我使用“A”表示第一个客户端，“B”表示第二个客户端，等等。客户的数量是10，我不记得确切的批次大小，可能是50。但批处理的大小越大，您就越能清楚地看到模式。权衡的是，大批量计算T-SNE向量需要更长的时间.
> 
> Thanks. What is the number of iterations of client training? Do you see my code is correct? Various colors represent the activation vectors for different classes, while the letters denote the device IDs. How to ensure that various colors represent different types of activation vectors? plt.text(X[i, 0], X[i, 1], user_list[i // batch_size], color=color_list[i // batch_size]) [T-SNE_V1.docx](https://github.com/weichennone/FedMAX/files/7665415/T-SNE_V1.docx)

Your code looks reasonable. 
I did 600-3000 epochs for the training iteration. But to recreate the TSNE in the paper, I mainly focus on the first 10 iterations. Because each time after FedAvg, models of clients will be the same, and there'll be less difference among the activations of each client. 
To recreate "Various colors represent the activation vectors for different classes, while the letters denote the device IDs.", you need to store more information from the clients, like the label of each activation (because you have the label of each input, it's equal to getting the label of each activation). Then after sending this information to "plot_embedding", and change plt.text(X[i, 0], X[i, 1], user_list[i // batch_size], color=color_list[i // batch_size]) to plt.text(X[i, 0], X[i, 1], user_list[i // batch_size], color=color_list[label_index]), where label_index is how you retrieve the index of corresponding label for each activation.
It may take some effort to modify the code, but I think it should be straightforward. Good luck!

**Comment by xiuhaoLiang** [comment]
> 
Thanks for your answer. Now, I have modified the code to get the label_index that each client owns.  However, I still have a question. Because each client has two labels, how to determine which part of the activation vector belongs to which label (or class).

**Comment by weichennone** [comment]
> > 
> 
> Thanks for your answer. Now, I have modified the code to get the label_index that each client owns. However, I still have a question. Because each client has two labels, how to determine which part of the activation vector belongs to which label (or class).

When the model does the classification, it needs to calculate the loss between prediction and "true labels". This is how to determine the corresponding labels to activations.

**Comment by xiuhaoLiang** [comment]
> > > 
> > 
> > 
> > Thanks for your answer. Now, I have modified the code to get the label_index that each client owns. However, I still have a question. Because each client has two labels, how to determine which part of the activation vector belongs to which label (or class).
> 
> When the model does the classification, it needs to calculate the loss between prediction and "true labels". This is how to determine the corresponding labels to activations.

Your mean is that using the trainable model to predict the test data (fixed or known data) after one client train the model using local data, thus determining a 512D activation vector belongs to which class. Or other methods?

**Comment by xiuhaoLiang** [comment]
Hi, bro. I wrote the code to draw the t-SNE plot according to your idea, but there is no clustering phenomenon. I think there are still some problems with my code, so the t-SNE plot of your paper is not reproduced.
![Figure 2021-12-13 104232](https://user-images.githubusercontent.com/57279277/145744965-b55fb4f6-3201-4cb7-9fd0-a2c025a9f660.png)

**Comment by weichennone** [comment]
> Hi, bro. I wrote the code to draw the t-SNE plot according to your idea, but there is no clustering phenomenon. I think there are still some problems with my code, so the t-SNE plot of your paper is not reproduced. ![Figure 2021-12-13 104232](https://user-images.githubusercontent.com/57279277/145744965-b55fb4f6-3201-4cb7-9fd0-a2c025a9f660.png)

Hi, I just sent you the debugging code to your email. It contains all the code you need to recreate TSNE plot. Hope that can help you.
And you need more epochs (check epoch number in paper) to find clusters forming in the plot, so make sure you have the same epoch number.
